spring:
  application:
    name: config-server
#git uri , username , password 
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yagnimurali/cgi-ms-config-server
          username: yagnimurali        
          password: 
          clone-on-start: true
          default-label: main
server:
  port: 8888